/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public final class FMOD_STUDIO_PARAMETER_TYPE {
  public final static FMOD_STUDIO_PARAMETER_TYPE FMOD_STUDIO_PARAMETER_GAME_CONTROLLED = new FMOD_STUDIO_PARAMETER_TYPE("FMOD_STUDIO_PARAMETER_GAME_CONTROLLED");
  public final static FMOD_STUDIO_PARAMETER_TYPE FMOD_STUDIO_PARAMETER_AUTOMATIC_DISTANCE = new FMOD_STUDIO_PARAMETER_TYPE("FMOD_STUDIO_PARAMETER_AUTOMATIC_DISTANCE");
  public final static FMOD_STUDIO_PARAMETER_TYPE FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_CONE_ANGLE = new FMOD_STUDIO_PARAMETER_TYPE("FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_CONE_ANGLE");
  public final static FMOD_STUDIO_PARAMETER_TYPE FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_ORIENTATION = new FMOD_STUDIO_PARAMETER_TYPE("FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_ORIENTATION");
  public final static FMOD_STUDIO_PARAMETER_TYPE FMOD_STUDIO_PARAMETER_AUTOMATIC_DIRECTION = new FMOD_STUDIO_PARAMETER_TYPE("FMOD_STUDIO_PARAMETER_AUTOMATIC_DIRECTION");
  public final static FMOD_STUDIO_PARAMETER_TYPE FMOD_STUDIO_PARAMETER_AUTOMATIC_ELEVATION = new FMOD_STUDIO_PARAMETER_TYPE("FMOD_STUDIO_PARAMETER_AUTOMATIC_ELEVATION");
  public final static FMOD_STUDIO_PARAMETER_TYPE FMOD_STUDIO_PARAMETER_AUTOMATIC_LISTENER_ORIENTATION = new FMOD_STUDIO_PARAMETER_TYPE("FMOD_STUDIO_PARAMETER_AUTOMATIC_LISTENER_ORIENTATION");
  public final static FMOD_STUDIO_PARAMETER_TYPE FMOD_STUDIO_PARAMETER_MAX = new FMOD_STUDIO_PARAMETER_TYPE("FMOD_STUDIO_PARAMETER_MAX");
  public final static FMOD_STUDIO_PARAMETER_TYPE FMOD_STUDIO_PARAMETER_FORCEINT = new FMOD_STUDIO_PARAMETER_TYPE("FMOD_STUDIO_PARAMETER_FORCEINT", fmodJNI.FMOD_STUDIO_PARAMETER_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_STUDIO_PARAMETER_TYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_STUDIO_PARAMETER_TYPE.class + " with value " + swigValue);
  }

  private FMOD_STUDIO_PARAMETER_TYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_STUDIO_PARAMETER_TYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_STUDIO_PARAMETER_TYPE(String swigName, FMOD_STUDIO_PARAMETER_TYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_STUDIO_PARAMETER_TYPE[] swigValues = { FMOD_STUDIO_PARAMETER_GAME_CONTROLLED, FMOD_STUDIO_PARAMETER_AUTOMATIC_DISTANCE, FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_CONE_ANGLE, FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_ORIENTATION, FMOD_STUDIO_PARAMETER_AUTOMATIC_DIRECTION, FMOD_STUDIO_PARAMETER_AUTOMATIC_ELEVATION, FMOD_STUDIO_PARAMETER_AUTOMATIC_LISTENER_ORIENTATION, FMOD_STUDIO_PARAMETER_MAX, FMOD_STUDIO_PARAMETER_FORCEINT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

