/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public final class FMOD_CHANNELCONTROL_TYPE {
  public final static FMOD_CHANNELCONTROL_TYPE FMOD_CHANNELCONTROL_CHANNEL = new FMOD_CHANNELCONTROL_TYPE("FMOD_CHANNELCONTROL_CHANNEL");
  public final static FMOD_CHANNELCONTROL_TYPE FMOD_CHANNELCONTROL_CHANNELGROUP = new FMOD_CHANNELCONTROL_TYPE("FMOD_CHANNELCONTROL_CHANNELGROUP");
  public final static FMOD_CHANNELCONTROL_TYPE FMOD_CHANNELCONTROL_FORCEINT = new FMOD_CHANNELCONTROL_TYPE("FMOD_CHANNELCONTROL_FORCEINT", fmodJNI.FMOD_CHANNELCONTROL_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_CHANNELCONTROL_TYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_CHANNELCONTROL_TYPE.class + " with value " + swigValue);
  }

  private FMOD_CHANNELCONTROL_TYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_CHANNELCONTROL_TYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_CHANNELCONTROL_TYPE(String swigName, FMOD_CHANNELCONTROL_TYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_CHANNELCONTROL_TYPE[] swigValues = { FMOD_CHANNELCONTROL_CHANNEL, FMOD_CHANNELCONTROL_CHANNELGROUP, FMOD_CHANNELCONTROL_FORCEINT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

