/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public final class FMOD_STUDIO_PLAYBACK_STATE {
  public final static FMOD_STUDIO_PLAYBACK_STATE FMOD_STUDIO_PLAYBACK_PLAYING = new FMOD_STUDIO_PLAYBACK_STATE("FMOD_STUDIO_PLAYBACK_PLAYING");
  public final static FMOD_STUDIO_PLAYBACK_STATE FMOD_STUDIO_PLAYBACK_SUSTAINING = new FMOD_STUDIO_PLAYBACK_STATE("FMOD_STUDIO_PLAYBACK_SUSTAINING");
  public final static FMOD_STUDIO_PLAYBACK_STATE FMOD_STUDIO_PLAYBACK_STOPPED = new FMOD_STUDIO_PLAYBACK_STATE("FMOD_STUDIO_PLAYBACK_STOPPED");
  public final static FMOD_STUDIO_PLAYBACK_STATE FMOD_STUDIO_PLAYBACK_STARTING = new FMOD_STUDIO_PLAYBACK_STATE("FMOD_STUDIO_PLAYBACK_STARTING");
  public final static FMOD_STUDIO_PLAYBACK_STATE FMOD_STUDIO_PLAYBACK_STOPPING = new FMOD_STUDIO_PLAYBACK_STATE("FMOD_STUDIO_PLAYBACK_STOPPING");
  public final static FMOD_STUDIO_PLAYBACK_STATE FMOD_STUDIO_PLAYBACK_FORCEINT = new FMOD_STUDIO_PLAYBACK_STATE("FMOD_STUDIO_PLAYBACK_FORCEINT", fmodJNI.FMOD_STUDIO_PLAYBACK_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_STUDIO_PLAYBACK_STATE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_STUDIO_PLAYBACK_STATE.class + " with value " + swigValue);
  }

  private FMOD_STUDIO_PLAYBACK_STATE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_STUDIO_PLAYBACK_STATE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_STUDIO_PLAYBACK_STATE(String swigName, FMOD_STUDIO_PLAYBACK_STATE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_STUDIO_PLAYBACK_STATE[] swigValues = { FMOD_STUDIO_PLAYBACK_PLAYING, FMOD_STUDIO_PLAYBACK_SUSTAINING, FMOD_STUDIO_PLAYBACK_STOPPED, FMOD_STUDIO_PLAYBACK_STARTING, FMOD_STUDIO_PLAYBACK_STOPPING, FMOD_STUDIO_PLAYBACK_FORCEINT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

