/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public final class FMOD_STUDIO_EVENT_PROPERTY {
  public final static FMOD_STUDIO_EVENT_PROPERTY FMOD_STUDIO_EVENT_PROPERTY_CHANNELPRIORITY = new FMOD_STUDIO_EVENT_PROPERTY("FMOD_STUDIO_EVENT_PROPERTY_CHANNELPRIORITY");
  public final static FMOD_STUDIO_EVENT_PROPERTY FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_DELAY = new FMOD_STUDIO_EVENT_PROPERTY("FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_DELAY");
  public final static FMOD_STUDIO_EVENT_PROPERTY FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_LOOKAHEAD = new FMOD_STUDIO_EVENT_PROPERTY("FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_LOOKAHEAD");
  public final static FMOD_STUDIO_EVENT_PROPERTY FMOD_STUDIO_EVENT_PROPERTY_MAX = new FMOD_STUDIO_EVENT_PROPERTY("FMOD_STUDIO_EVENT_PROPERTY_MAX");
  public final static FMOD_STUDIO_EVENT_PROPERTY FMOD_STUDIO_EVENT_PROPERTY_FORCEINT = new FMOD_STUDIO_EVENT_PROPERTY("FMOD_STUDIO_EVENT_PROPERTY_FORCEINT", fmodJNI.FMOD_STUDIO_EVENT_PROPERTY_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_STUDIO_EVENT_PROPERTY swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_STUDIO_EVENT_PROPERTY.class + " with value " + swigValue);
  }

  private FMOD_STUDIO_EVENT_PROPERTY(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_STUDIO_EVENT_PROPERTY(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_STUDIO_EVENT_PROPERTY(String swigName, FMOD_STUDIO_EVENT_PROPERTY swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_STUDIO_EVENT_PROPERTY[] swigValues = { FMOD_STUDIO_EVENT_PROPERTY_CHANNELPRIORITY, FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_DELAY, FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_LOOKAHEAD, FMOD_STUDIO_EVENT_PROPERTY_MAX, FMOD_STUDIO_EVENT_PROPERTY_FORCEINT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

