/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public final class FMOD_STUDIO_LOAD_MEMORY_MODE {
  public final static FMOD_STUDIO_LOAD_MEMORY_MODE FMOD_STUDIO_LOAD_MEMORY = new FMOD_STUDIO_LOAD_MEMORY_MODE("FMOD_STUDIO_LOAD_MEMORY");
  public final static FMOD_STUDIO_LOAD_MEMORY_MODE FMOD_STUDIO_LOAD_MEMORY_POINT = new FMOD_STUDIO_LOAD_MEMORY_MODE("FMOD_STUDIO_LOAD_MEMORY_POINT");
  public final static FMOD_STUDIO_LOAD_MEMORY_MODE FMOD_STUDIO_LOAD_MEMORY_FORCEINT = new FMOD_STUDIO_LOAD_MEMORY_MODE("FMOD_STUDIO_LOAD_MEMORY_FORCEINT", fmodJNI.FMOD_STUDIO_LOAD_MEMORY_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_STUDIO_LOAD_MEMORY_MODE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_STUDIO_LOAD_MEMORY_MODE.class + " with value " + swigValue);
  }

  private FMOD_STUDIO_LOAD_MEMORY_MODE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_STUDIO_LOAD_MEMORY_MODE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_STUDIO_LOAD_MEMORY_MODE(String swigName, FMOD_STUDIO_LOAD_MEMORY_MODE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_STUDIO_LOAD_MEMORY_MODE[] swigValues = { FMOD_STUDIO_LOAD_MEMORY, FMOD_STUDIO_LOAD_MEMORY_POINT, FMOD_STUDIO_LOAD_MEMORY_FORCEINT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

