/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public class FMOD_STUDIO_USER_PROPERTY {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FMOD_STUDIO_USER_PROPERTY(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_USER_PROPERTY obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODJNI.delete_FMOD_STUDIO_USER_PROPERTY(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean equals(Object obj) {
  	if(obj == this) return true;
  	if(obj == null) return false;
  	if (! (obj instanceof FMOD_STUDIO_USER_PROPERTY)) return false;
    return this.swigCPtr == ((FMOD_STUDIO_USER_PROPERTY)obj).swigCPtr;
  }
  public int hashCode() {
     return (int)swigCPtr;
  }

  public void setName(String value) {
    FMODJNI.FMOD_STUDIO_USER_PROPERTY_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return FMODJNI.FMOD_STUDIO_USER_PROPERTY_name_get(swigCPtr, this);
  }

  public void setType(FMOD_STUDIO_USER_PROPERTY_TYPE value) {
    FMODJNI.FMOD_STUDIO_USER_PROPERTY_type_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_STUDIO_USER_PROPERTY_TYPE getType() {
    return FMOD_STUDIO_USER_PROPERTY_TYPE.swigToEnum(FMODJNI.FMOD_STUDIO_USER_PROPERTY_type_get(swigCPtr, this));
  }

  public void setIntValue(int value) {
    FMODJNI.FMOD_STUDIO_USER_PROPERTY_intValue_set(swigCPtr, this, value);
  }

  public int getIntValue() {
    return FMODJNI.FMOD_STUDIO_USER_PROPERTY_intValue_get(swigCPtr, this);
  }

  public void setBoolValue(int value) {
    FMODJNI.FMOD_STUDIO_USER_PROPERTY_boolValue_set(swigCPtr, this, value);
  }

  public int getBoolValue() {
    return FMODJNI.FMOD_STUDIO_USER_PROPERTY_boolValue_get(swigCPtr, this);
  }

  public void setFloatValue(float value) {
    FMODJNI.FMOD_STUDIO_USER_PROPERTY_floatValue_set(swigCPtr, this, value);
  }

  public float getFloatValue() {
    return FMODJNI.FMOD_STUDIO_USER_PROPERTY_floatValue_get(swigCPtr, this);
  }

  public void setStringValue(String value) {
    FMODJNI.FMOD_STUDIO_USER_PROPERTY_stringValue_set(swigCPtr, this, value);
  }

  public String getStringValue() {
    return FMODJNI.FMOD_STUDIO_USER_PROPERTY_stringValue_get(swigCPtr, this);
  }

  public FMOD_STUDIO_USER_PROPERTY() {
    this(FMODJNI.new_FMOD_STUDIO_USER_PROPERTY(), true);
  }

}
