/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public class FMOD_TAG {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FMOD_TAG(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_TAG obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fmodJNI.delete_FMOD_TAG(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(FMOD_TAGTYPE value) {
    fmodJNI.FMOD_TAG_type_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_TAGTYPE getType() {
    return FMOD_TAGTYPE.swigToEnum(fmodJNI.FMOD_TAG_type_get(swigCPtr, this));
  }

  public void setDatatype(FMOD_TAGDATATYPE value) {
    fmodJNI.FMOD_TAG_datatype_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_TAGDATATYPE getDatatype() {
    return FMOD_TAGDATATYPE.swigToEnum(fmodJNI.FMOD_TAG_datatype_get(swigCPtr, this));
  }

  public void setName(String value) {
    fmodJNI.FMOD_TAG_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return fmodJNI.FMOD_TAG_name_get(swigCPtr, this);
  }

  public void setData(SWIGTYPE_p_void value) {
    fmodJNI.FMOD_TAG_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData() {
    long cPtr = fmodJNI.FMOD_TAG_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setDatalen(long value) {
    fmodJNI.FMOD_TAG_datalen_set(swigCPtr, this, value);
  }

  public long getDatalen() {
    return fmodJNI.FMOD_TAG_datalen_get(swigCPtr, this);
  }

  public void setUpdated(int value) {
    fmodJNI.FMOD_TAG_updated_set(swigCPtr, this, value);
  }

  public int getUpdated() {
    return fmodJNI.FMOD_TAG_updated_get(swigCPtr, this);
  }

  public FMOD_TAG() {
    this(fmodJNI.new_FMOD_TAG(), true);
  }

}
