/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public class FMOD_STUDIO_BUFFER_USAGE {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FMOD_STUDIO_BUFFER_USAGE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_BUFFER_USAGE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODJNI.delete_FMOD_STUDIO_BUFFER_USAGE(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStudioCommandQueue(FMOD_STUDIO_BUFFER_INFO value) {
    FMODJNI.FMOD_STUDIO_BUFFER_USAGE_studioCommandQueue_set(swigCPtr, this, FMOD_STUDIO_BUFFER_INFO.getCPtr(value), value);
  }

  public FMOD_STUDIO_BUFFER_INFO getStudioCommandQueue() {
    long cPtr = FMODJNI.FMOD_STUDIO_BUFFER_USAGE_studioCommandQueue_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_STUDIO_BUFFER_INFO(cPtr, false);
  }

  public void setStudioHandle(FMOD_STUDIO_BUFFER_INFO value) {
    FMODJNI.FMOD_STUDIO_BUFFER_USAGE_studioHandle_set(swigCPtr, this, FMOD_STUDIO_BUFFER_INFO.getCPtr(value), value);
  }

  public FMOD_STUDIO_BUFFER_INFO getStudioHandle() {
    long cPtr = FMODJNI.FMOD_STUDIO_BUFFER_USAGE_studioHandle_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_STUDIO_BUFFER_INFO(cPtr, false);
  }

  public FMOD_STUDIO_BUFFER_USAGE() {
    this(FMODJNI.new_FMOD_STUDIO_BUFFER_USAGE(), true);
  }

}
