/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public class FMOD_STUDIO_ADVANCEDSETTINGS {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_STUDIO_ADVANCEDSETTINGS(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_ADVANCEDSETTINGS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODJNI.delete_FMOD_STUDIO_ADVANCEDSETTINGS(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean equals(Object obj) {
  	if(obj == this) return true;
  	if(obj == null) return false;
  	if (! (obj instanceof FMOD_STUDIO_ADVANCEDSETTINGS)) return false;
    return this.swigCPtr == ((FMOD_STUDIO_ADVANCEDSETTINGS)obj).swigCPtr;
  }
  public int hashCode() {
     return (int)swigCPtr;
  }

  public void setCbSize(int value) {
    FMODJNI.FMOD_STUDIO_ADVANCEDSETTINGS_cbSize_set(swigCPtr, this, value);
  }

  public int getCbSize() {
    return FMODJNI.FMOD_STUDIO_ADVANCEDSETTINGS_cbSize_get(swigCPtr, this);
  }

  public void setCommandQueueSize(long value) {
    FMODJNI.FMOD_STUDIO_ADVANCEDSETTINGS_commandQueueSize_set(swigCPtr, this, value);
  }

  public long getCommandQueueSize() {
    return FMODJNI.FMOD_STUDIO_ADVANCEDSETTINGS_commandQueueSize_get(swigCPtr, this);
  }

  public void setHandleInitialSize(long value) {
    FMODJNI.FMOD_STUDIO_ADVANCEDSETTINGS_handleInitialSize_set(swigCPtr, this, value);
  }

  public long getHandleInitialSize() {
    return FMODJNI.FMOD_STUDIO_ADVANCEDSETTINGS_handleInitialSize_get(swigCPtr, this);
  }

  public void setStudioUpdatePeriod(int value) {
    FMODJNI.FMOD_STUDIO_ADVANCEDSETTINGS_studioUpdatePeriod_set(swigCPtr, this, value);
  }

  public int getStudioUpdatePeriod() {
    return FMODJNI.FMOD_STUDIO_ADVANCEDSETTINGS_studioUpdatePeriod_get(swigCPtr, this);
  }

  public void setIdleSampleDataPoolSize(int value) {
    FMODJNI.FMOD_STUDIO_ADVANCEDSETTINGS_idleSampleDataPoolSize_set(swigCPtr, this, value);
  }

  public int getIdleSampleDataPoolSize() {
    return FMODJNI.FMOD_STUDIO_ADVANCEDSETTINGS_idleSampleDataPoolSize_get(swigCPtr, this);
  }

  public FMOD_STUDIO_ADVANCEDSETTINGS() {
    this(FMODJNI.new_FMOD_STUDIO_ADVANCEDSETTINGS(), true);
  }

}
