/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public enum FMOD_CHANNELCONTROL_CALLBACK_TYPE {
  FMOD_CHANNELCONTROL_CALLBACK_END,
  FMOD_CHANNELCONTROL_CALLBACK_VIRTUALVOICE,
  FMOD_CHANNELCONTROL_CALLBACK_SYNCPOINT,
  FMOD_CHANNELCONTROL_CALLBACK_OCCLUSION,
  FMOD_CHANNELCONTROL_CALLBACK_MAX,
  FMOD_CHANNELCONTROL_CALLBACK_FORCEINT(FMODJNI.FMOD_CHANNELCONTROL_CALLBACK_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public static FMOD_CHANNELCONTROL_CALLBACK_TYPE swigToEnum(int swigValue) {
    FMOD_CHANNELCONTROL_CALLBACK_TYPE[] swigValues = FMOD_CHANNELCONTROL_CALLBACK_TYPE.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (FMOD_CHANNELCONTROL_CALLBACK_TYPE swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + FMOD_CHANNELCONTROL_CALLBACK_TYPE.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private FMOD_CHANNELCONTROL_CALLBACK_TYPE() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private FMOD_CHANNELCONTROL_CALLBACK_TYPE(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private FMOD_CHANNELCONTROL_CALLBACK_TYPE(FMOD_CHANNELCONTROL_CALLBACK_TYPE swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

