/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public enum FMOD_ERRORCALLBACK_INSTANCETYPE {
  FMOD_ERRORCALLBACK_INSTANCETYPE_NONE,
  FMOD_ERRORCALLBACK_INSTANCETYPE_SYSTEM,
  FMOD_ERRORCALLBACK_INSTANCETYPE_CHANNEL,
  FMOD_ERRORCALLBACK_INSTANCETYPE_CHANNELGROUP,
  FMOD_ERRORCALLBACK_INSTANCETYPE_CHANNELCONTROL,
  FMOD_ERRORCALLBACK_INSTANCETYPE_SOUND,
  FMOD_ERRORCALLBACK_INSTANCETYPE_SOUNDGROUP,
  FMOD_ERRORCALLBACK_INSTANCETYPE_DSP,
  FMOD_ERRORCALLBACK_INSTANCETYPE_DSPCONNECTION,
  FMOD_ERRORCALLBACK_INSTANCETYPE_GEOMETRY,
  FMOD_ERRORCALLBACK_INSTANCETYPE_REVERB3D,
  FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_SYSTEM,
  FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_EVENTDESCRIPTION,
  FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_EVENTINSTANCE,
  FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_PARAMETERINSTANCE,
  FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_BUS,
  FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_VCA,
  FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_BANK,
  FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_COMMANDREPLAY,
  FMOD_ERRORCALLBACK_INSTANCETYPE_FORCEINT(FMODJNI.FMOD_ERRORCALLBACK_INSTANCETYPE_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public static FMOD_ERRORCALLBACK_INSTANCETYPE swigToEnum(int swigValue) {
    FMOD_ERRORCALLBACK_INSTANCETYPE[] swigValues = FMOD_ERRORCALLBACK_INSTANCETYPE.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (FMOD_ERRORCALLBACK_INSTANCETYPE swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + FMOD_ERRORCALLBACK_INSTANCETYPE.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private FMOD_ERRORCALLBACK_INSTANCETYPE() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private FMOD_ERRORCALLBACK_INSTANCETYPE(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private FMOD_ERRORCALLBACK_INSTANCETYPE(FMOD_ERRORCALLBACK_INSTANCETYPE swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

