/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public final class FMOD_OUTPUTTYPE {
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_AUTODETECT = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_AUTODETECT");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_UNKNOWN = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_UNKNOWN");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_NOSOUND = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_NOSOUND");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_WAVWRITER = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_WAVWRITER");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_NOSOUND_NRT = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_NOSOUND_NRT");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_WAVWRITER_NRT = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_WAVWRITER_NRT");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_DSOUND = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_DSOUND");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_WINMM = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_WINMM");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_WASAPI = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_WASAPI");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_ASIO = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_ASIO");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_PULSEAUDIO = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_PULSEAUDIO");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_ALSA = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_ALSA");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_COREAUDIO = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_COREAUDIO");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_XBOX360 = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_XBOX360");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_PS3 = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_PS3");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_AUDIOTRACK = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_AUDIOTRACK");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_OPENSL = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_OPENSL");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_WIIU = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_WIIU");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_AUDIOOUT = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_AUDIOOUT");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_MAX = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_MAX");
  public final static FMOD_OUTPUTTYPE FMOD_OUTPUTTYPE_FORCEINT = new FMOD_OUTPUTTYPE("FMOD_OUTPUTTYPE_FORCEINT", fmodJNI.FMOD_OUTPUTTYPE_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_OUTPUTTYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_OUTPUTTYPE.class + " with value " + swigValue);
  }

  private FMOD_OUTPUTTYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_OUTPUTTYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_OUTPUTTYPE(String swigName, FMOD_OUTPUTTYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_OUTPUTTYPE[] swigValues = { FMOD_OUTPUTTYPE_AUTODETECT, FMOD_OUTPUTTYPE_UNKNOWN, FMOD_OUTPUTTYPE_NOSOUND, FMOD_OUTPUTTYPE_WAVWRITER, FMOD_OUTPUTTYPE_NOSOUND_NRT, FMOD_OUTPUTTYPE_WAVWRITER_NRT, FMOD_OUTPUTTYPE_DSOUND, FMOD_OUTPUTTYPE_WINMM, FMOD_OUTPUTTYPE_WASAPI, FMOD_OUTPUTTYPE_ASIO, FMOD_OUTPUTTYPE_PULSEAUDIO, FMOD_OUTPUTTYPE_ALSA, FMOD_OUTPUTTYPE_COREAUDIO, FMOD_OUTPUTTYPE_XBOX360, FMOD_OUTPUTTYPE_PS3, FMOD_OUTPUTTYPE_AUDIOTRACK, FMOD_OUTPUTTYPE_OPENSL, FMOD_OUTPUTTYPE_WIIU, FMOD_OUTPUTTYPE_AUDIOOUT, FMOD_OUTPUTTYPE_MAX, FMOD_OUTPUTTYPE_FORCEINT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

