/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public class FMOD_3D_ATTRIBUTES {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FMOD_3D_ATTRIBUTES(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_3D_ATTRIBUTES obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODJNI.delete_FMOD_3D_ATTRIBUTES(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean equals(Object obj) {
  	if(obj == this) return true;
  	if(obj == null) return false;
  	if (! (obj instanceof FMOD_3D_ATTRIBUTES)) return false;
    return this.swigCPtr == ((FMOD_3D_ATTRIBUTES)obj).swigCPtr;
  }
  public int hashCode() {
     return (int)swigCPtr;
  }

  public void setPosition(FMOD_VECTOR value) {
    FMODJNI.FMOD_3D_ATTRIBUTES_position_set(swigCPtr, this, FMOD_VECTOR.getCPtr(value), value);
  }

  public FMOD_VECTOR getPosition() {
    long cPtr = FMODJNI.FMOD_3D_ATTRIBUTES_position_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_VECTOR(cPtr, false);
  }

  public void setVelocity(FMOD_VECTOR value) {
    FMODJNI.FMOD_3D_ATTRIBUTES_velocity_set(swigCPtr, this, FMOD_VECTOR.getCPtr(value), value);
  }

  public FMOD_VECTOR getVelocity() {
    long cPtr = FMODJNI.FMOD_3D_ATTRIBUTES_velocity_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_VECTOR(cPtr, false);
  }

  public void setForward(FMOD_VECTOR value) {
    FMODJNI.FMOD_3D_ATTRIBUTES_forward_set(swigCPtr, this, FMOD_VECTOR.getCPtr(value), value);
  }

  public FMOD_VECTOR getForward() {
    long cPtr = FMODJNI.FMOD_3D_ATTRIBUTES_forward_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_VECTOR(cPtr, false);
  }

  public void setUp(FMOD_VECTOR value) {
    FMODJNI.FMOD_3D_ATTRIBUTES_up_set(swigCPtr, this, FMOD_VECTOR.getCPtr(value), value);
  }

  public FMOD_VECTOR getUp() {
    long cPtr = FMODJNI.FMOD_3D_ATTRIBUTES_up_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_VECTOR(cPtr, false);
  }

  public FMOD_3D_ATTRIBUTES() {
    this(FMODJNI.new_FMOD_3D_ATTRIBUTES(), true);
  }

}
