/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public enum FMOD_STUDIO_PARAMETER_TYPE {
  FMOD_STUDIO_PARAMETER_GAME_CONTROLLED,
  FMOD_STUDIO_PARAMETER_AUTOMATIC_DISTANCE,
  FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_CONE_ANGLE,
  FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_ORIENTATION,
  FMOD_STUDIO_PARAMETER_AUTOMATIC_DIRECTION,
  FMOD_STUDIO_PARAMETER_AUTOMATIC_ELEVATION,
  FMOD_STUDIO_PARAMETER_AUTOMATIC_LISTENER_ORIENTATION,
  FMOD_STUDIO_PARAMETER_MAX,
  FMOD_STUDIO_PARAMETER_FORCEINT(FMODJNI.FMOD_STUDIO_PARAMETER_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public static FMOD_STUDIO_PARAMETER_TYPE swigToEnum(int swigValue) {
    FMOD_STUDIO_PARAMETER_TYPE[] swigValues = FMOD_STUDIO_PARAMETER_TYPE.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (FMOD_STUDIO_PARAMETER_TYPE swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + FMOD_STUDIO_PARAMETER_TYPE.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private FMOD_STUDIO_PARAMETER_TYPE() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private FMOD_STUDIO_PARAMETER_TYPE(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private FMOD_STUDIO_PARAMETER_TYPE(FMOD_STUDIO_PARAMETER_TYPE swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

