/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public class FMOD_STUDIO_SOUND_INFO {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FMOD_STUDIO_SOUND_INFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_SOUND_INFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODJNI.delete_FMOD_STUDIO_SOUND_INFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName_or_data(String value) {
    FMODJNI.FMOD_STUDIO_SOUND_INFO_name_or_data_set(swigCPtr, this, value);
  }

  public String getName_or_data() {
    return FMODJNI.FMOD_STUDIO_SOUND_INFO_name_or_data_get(swigCPtr, this);
  }

  public void setMode(long value) {
    FMODJNI.FMOD_STUDIO_SOUND_INFO_mode_set(swigCPtr, this, value);
  }

  public long getMode() {
    return FMODJNI.FMOD_STUDIO_SOUND_INFO_mode_get(swigCPtr, this);
  }

  public void setExinfo(FMOD_CREATESOUNDEXINFO value) {
    FMODJNI.FMOD_STUDIO_SOUND_INFO_exinfo_set(swigCPtr, this, FMOD_CREATESOUNDEXINFO.getCPtr(value), value);
  }

  public FMOD_CREATESOUNDEXINFO getExinfo() {
    long cPtr = FMODJNI.FMOD_STUDIO_SOUND_INFO_exinfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_CREATESOUNDEXINFO(cPtr, false);
  }

  public void setSubsoundIndex(int value) {
    FMODJNI.FMOD_STUDIO_SOUND_INFO_subsoundIndex_set(swigCPtr, this, value);
  }

  public int getSubsoundIndex() {
    return FMODJNI.FMOD_STUDIO_SOUND_INFO_subsoundIndex_get(swigCPtr, this);
  }

  public FMOD_STUDIO_SOUND_INFO() {
    this(FMODJNI.new_FMOD_STUDIO_SOUND_INFO(), true);
  }

}
