/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public class FMOD_STUDIO_COMMAND_INFO {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_STUDIO_COMMAND_INFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_COMMAND_INFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODJNI.delete_FMOD_STUDIO_COMMAND_INFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean equals(Object obj) {
  	if(obj == this) return true;
  	if(obj == null) return false;
  	if (! (obj instanceof FMOD_STUDIO_COMMAND_INFO)) return false;
    return this.swigCPtr == ((FMOD_STUDIO_COMMAND_INFO)obj).swigCPtr;
  }
  public int hashCode() {
     return (int)swigCPtr;
  }

  public void setCommandname(String value) {
    FMODJNI.FMOD_STUDIO_COMMAND_INFO_commandname_set(swigCPtr, this, value);
  }

  public String getCommandname() {
    return FMODJNI.FMOD_STUDIO_COMMAND_INFO_commandname_get(swigCPtr, this);
  }

  public void setParentcommandindex(int value) {
    FMODJNI.FMOD_STUDIO_COMMAND_INFO_parentcommandindex_set(swigCPtr, this, value);
  }

  public int getParentcommandindex() {
    return FMODJNI.FMOD_STUDIO_COMMAND_INFO_parentcommandindex_get(swigCPtr, this);
  }

  public void setFramenumber(int value) {
    FMODJNI.FMOD_STUDIO_COMMAND_INFO_framenumber_set(swigCPtr, this, value);
  }

  public int getFramenumber() {
    return FMODJNI.FMOD_STUDIO_COMMAND_INFO_framenumber_get(swigCPtr, this);
  }

  public void setFrametime(float value) {
    FMODJNI.FMOD_STUDIO_COMMAND_INFO_frametime_set(swigCPtr, this, value);
  }

  public float getFrametime() {
    return FMODJNI.FMOD_STUDIO_COMMAND_INFO_frametime_get(swigCPtr, this);
  }

  public void setInstancetype(FMOD_STUDIO_INSTANCETYPE value) {
    FMODJNI.FMOD_STUDIO_COMMAND_INFO_instancetype_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_STUDIO_INSTANCETYPE getInstancetype() {
    return FMOD_STUDIO_INSTANCETYPE.swigToEnum(FMODJNI.FMOD_STUDIO_COMMAND_INFO_instancetype_get(swigCPtr, this));
  }

  public void setOutputtype(FMOD_STUDIO_INSTANCETYPE value) {
    FMODJNI.FMOD_STUDIO_COMMAND_INFO_outputtype_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_STUDIO_INSTANCETYPE getOutputtype() {
    return FMOD_STUDIO_INSTANCETYPE.swigToEnum(FMODJNI.FMOD_STUDIO_COMMAND_INFO_outputtype_get(swigCPtr, this));
  }

  public void setInstancehandle(long value) {
    FMODJNI.FMOD_STUDIO_COMMAND_INFO_instancehandle_set(swigCPtr, this, value);
  }

  public long getInstancehandle() {
    return FMODJNI.FMOD_STUDIO_COMMAND_INFO_instancehandle_get(swigCPtr, this);
  }

  public void setOutputhandle(long value) {
    FMODJNI.FMOD_STUDIO_COMMAND_INFO_outputhandle_set(swigCPtr, this, value);
  }

  public long getOutputhandle() {
    return FMODJNI.FMOD_STUDIO_COMMAND_INFO_outputhandle_get(swigCPtr, this);
  }

  public FMOD_STUDIO_COMMAND_INFO() {
    this(FMODJNI.new_FMOD_STUDIO_COMMAND_INFO(), true);
  }

}
