/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public final class FMOD_DSPCONNECTION_TYPE {
  public final static FMOD_DSPCONNECTION_TYPE FMOD_DSPCONNECTION_TYPE_STANDARD = new FMOD_DSPCONNECTION_TYPE("FMOD_DSPCONNECTION_TYPE_STANDARD");
  public final static FMOD_DSPCONNECTION_TYPE FMOD_DSPCONNECTION_TYPE_SIDECHAIN = new FMOD_DSPCONNECTION_TYPE("FMOD_DSPCONNECTION_TYPE_SIDECHAIN");
  public final static FMOD_DSPCONNECTION_TYPE FMOD_DSPCONNECTION_TYPE_SEND = new FMOD_DSPCONNECTION_TYPE("FMOD_DSPCONNECTION_TYPE_SEND");
  public final static FMOD_DSPCONNECTION_TYPE FMOD_DSPCONNECTION_TYPE_SEND_SIDECHAIN = new FMOD_DSPCONNECTION_TYPE("FMOD_DSPCONNECTION_TYPE_SEND_SIDECHAIN");
  public final static FMOD_DSPCONNECTION_TYPE FMOD_DSPCONNECTION_TYPE_MAX = new FMOD_DSPCONNECTION_TYPE("FMOD_DSPCONNECTION_TYPE_MAX");
  public final static FMOD_DSPCONNECTION_TYPE FMOD_DSPCONNECTION_TYPE_FORCEINT = new FMOD_DSPCONNECTION_TYPE("FMOD_DSPCONNECTION_TYPE_FORCEINT", fmodJNI.FMOD_DSPCONNECTION_TYPE_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_DSPCONNECTION_TYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_DSPCONNECTION_TYPE.class + " with value " + swigValue);
  }

  private FMOD_DSPCONNECTION_TYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_DSPCONNECTION_TYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_DSPCONNECTION_TYPE(String swigName, FMOD_DSPCONNECTION_TYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_DSPCONNECTION_TYPE[] swigValues = { FMOD_DSPCONNECTION_TYPE_STANDARD, FMOD_DSPCONNECTION_TYPE_SIDECHAIN, FMOD_DSPCONNECTION_TYPE_SEND, FMOD_DSPCONNECTION_TYPE_SEND_SIDECHAIN, FMOD_DSPCONNECTION_TYPE_MAX, FMOD_DSPCONNECTION_TYPE_FORCEINT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

