/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public enum FMOD_STUDIO_LOADING_STATE {
  FMOD_STUDIO_LOADING_STATE_UNLOADING,
  FMOD_STUDIO_LOADING_STATE_UNLOADED,
  FMOD_STUDIO_LOADING_STATE_LOADING,
  FMOD_STUDIO_LOADING_STATE_LOADED,
  FMOD_STUDIO_LOADING_STATE_ERROR,
  FMOD_STUDIO_LOADING_STATE_FORCEINT(FMODJNI.FMOD_STUDIO_LOADING_STATE_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public static FMOD_STUDIO_LOADING_STATE swigToEnum(int swigValue) {
    FMOD_STUDIO_LOADING_STATE[] swigValues = FMOD_STUDIO_LOADING_STATE.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (FMOD_STUDIO_LOADING_STATE swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + FMOD_STUDIO_LOADING_STATE.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private FMOD_STUDIO_LOADING_STATE() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private FMOD_STUDIO_LOADING_STATE(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private FMOD_STUDIO_LOADING_STATE(FMOD_STUDIO_LOADING_STATE swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

