/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public enum FMOD_DSP_RESAMPLER {
  FMOD_DSP_RESAMPLER_DEFAULT,
  FMOD_DSP_RESAMPLER_NOINTERP,
  FMOD_DSP_RESAMPLER_LINEAR,
  FMOD_DSP_RESAMPLER_CUBIC,
  FMOD_DSP_RESAMPLER_SPLINE,
  FMOD_DSP_RESAMPLER_MAX,
  FMOD_DSP_RESAMPLER_FORCEINT(FMODJNI.FMOD_DSP_RESAMPLER_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public static FMOD_DSP_RESAMPLER swigToEnum(int swigValue) {
    FMOD_DSP_RESAMPLER[] swigValues = FMOD_DSP_RESAMPLER.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (FMOD_DSP_RESAMPLER swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + FMOD_DSP_RESAMPLER.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private FMOD_DSP_RESAMPLER() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private FMOD_DSP_RESAMPLER(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private FMOD_DSP_RESAMPLER(FMOD_DSP_RESAMPLER swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

