/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public final class FMOD_PLUGINTYPE {
  public final static FMOD_PLUGINTYPE FMOD_PLUGINTYPE_OUTPUT = new FMOD_PLUGINTYPE("FMOD_PLUGINTYPE_OUTPUT");
  public final static FMOD_PLUGINTYPE FMOD_PLUGINTYPE_CODEC = new FMOD_PLUGINTYPE("FMOD_PLUGINTYPE_CODEC");
  public final static FMOD_PLUGINTYPE FMOD_PLUGINTYPE_DSP = new FMOD_PLUGINTYPE("FMOD_PLUGINTYPE_DSP");
  public final static FMOD_PLUGINTYPE FMOD_PLUGINTYPE_MAX = new FMOD_PLUGINTYPE("FMOD_PLUGINTYPE_MAX");
  public final static FMOD_PLUGINTYPE FMOD_PLUGINTYPE_FORCEINT = new FMOD_PLUGINTYPE("FMOD_PLUGINTYPE_FORCEINT", fmodJNI.FMOD_PLUGINTYPE_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_PLUGINTYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_PLUGINTYPE.class + " with value " + swigValue);
  }

  private FMOD_PLUGINTYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_PLUGINTYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_PLUGINTYPE(String swigName, FMOD_PLUGINTYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_PLUGINTYPE[] swigValues = { FMOD_PLUGINTYPE_OUTPUT, FMOD_PLUGINTYPE_CODEC, FMOD_PLUGINTYPE_DSP, FMOD_PLUGINTYPE_MAX, FMOD_PLUGINTYPE_FORCEINT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

