/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public enum FMOD_SOUNDGROUP_BEHAVIOR {
  FMOD_SOUNDGROUP_BEHAVIOR_FAIL,
  FMOD_SOUNDGROUP_BEHAVIOR_MUTE,
  FMOD_SOUNDGROUP_BEHAVIOR_STEALLOWEST,
  FMOD_SOUNDGROUP_BEHAVIOR_MAX,
  FMOD_SOUNDGROUP_BEHAVIOR_FORCEINT(FMODJNI.FMOD_SOUNDGROUP_BEHAVIOR_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public static FMOD_SOUNDGROUP_BEHAVIOR swigToEnum(int swigValue) {
    FMOD_SOUNDGROUP_BEHAVIOR[] swigValues = FMOD_SOUNDGROUP_BEHAVIOR.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (FMOD_SOUNDGROUP_BEHAVIOR swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + FMOD_SOUNDGROUP_BEHAVIOR.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private FMOD_SOUNDGROUP_BEHAVIOR() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private FMOD_SOUNDGROUP_BEHAVIOR(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private FMOD_SOUNDGROUP_BEHAVIOR(FMOD_SOUNDGROUP_BEHAVIOR swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

