/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public class FMOD_STUDIO_COMMAND_INFO {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_STUDIO_COMMAND_INFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_COMMAND_INFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODJNI.delete_FMOD_STUDIO_COMMAND_INFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean equals(Object obj) {
  	if(obj == this) return true;
  	if(obj == null) return false;
  	if (! (obj instanceof FMOD_STUDIO_COMMAND_INFO)) return false;
    return this.swigCPtr == ((FMOD_STUDIO_COMMAND_INFO)obj).swigCPtr;
  }
  public int hashCode() {
     return (int)swigCPtr;
  }

  public void setCommandName(String value) {
    FMODJNI.FMOD_STUDIO_COMMAND_INFO_commandName_set(swigCPtr, this, value);
  }

  public String getCommandName() {
    return FMODJNI.FMOD_STUDIO_COMMAND_INFO_commandName_get(swigCPtr, this);
  }

  public void setParentCommandIndex(int value) {
    FMODJNI.FMOD_STUDIO_COMMAND_INFO_parentCommandIndex_set(swigCPtr, this, value);
  }

  public int getParentCommandIndex() {
    return FMODJNI.FMOD_STUDIO_COMMAND_INFO_parentCommandIndex_get(swigCPtr, this);
  }

  public void setFrameNumber(int value) {
    FMODJNI.FMOD_STUDIO_COMMAND_INFO_frameNumber_set(swigCPtr, this, value);
  }

  public int getFrameNumber() {
    return FMODJNI.FMOD_STUDIO_COMMAND_INFO_frameNumber_get(swigCPtr, this);
  }

  public void setFrameTime(float value) {
    FMODJNI.FMOD_STUDIO_COMMAND_INFO_frameTime_set(swigCPtr, this, value);
  }

  public float getFrameTime() {
    return FMODJNI.FMOD_STUDIO_COMMAND_INFO_frameTime_get(swigCPtr, this);
  }

  public void setInstanceType(FMOD_STUDIO_INSTANCETYPE value) {
    FMODJNI.FMOD_STUDIO_COMMAND_INFO_instanceType_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_STUDIO_INSTANCETYPE getInstanceType() {
    return FMOD_STUDIO_INSTANCETYPE.swigToEnum(FMODJNI.FMOD_STUDIO_COMMAND_INFO_instanceType_get(swigCPtr, this));
  }

  public void setOutputType(FMOD_STUDIO_INSTANCETYPE value) {
    FMODJNI.FMOD_STUDIO_COMMAND_INFO_outputType_set(swigCPtr, this, value.swigValue());
  }

  public FMOD_STUDIO_INSTANCETYPE getOutputType() {
    return FMOD_STUDIO_INSTANCETYPE.swigToEnum(FMODJNI.FMOD_STUDIO_COMMAND_INFO_outputType_get(swigCPtr, this));
  }

  public void setInstanceHandle(long value) {
    FMODJNI.FMOD_STUDIO_COMMAND_INFO_instanceHandle_set(swigCPtr, this, value);
  }

  public long getInstanceHandle() {
    return FMODJNI.FMOD_STUDIO_COMMAND_INFO_instanceHandle_get(swigCPtr, this);
  }

  public void setOutputHandle(long value) {
    FMODJNI.FMOD_STUDIO_COMMAND_INFO_outputHandle_set(swigCPtr, this, value);
  }

  public long getOutputHandle() {
    return FMODJNI.FMOD_STUDIO_COMMAND_INFO_outputHandle_get(swigCPtr, this);
  }

  public FMOD_STUDIO_COMMAND_INFO() {
    this(FMODJNI.new_FMOD_STUDIO_COMMAND_INFO(), true);
  }

}
