/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public class FMOD_VECTOR {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_VECTOR(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_VECTOR obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODJNI.delete_FMOD_VECTOR(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean equals(Object obj) {
  	if(obj == this) return true;
  	if(obj == null) return false;
  	if (! (obj instanceof FMOD_VECTOR)) return false;
    return this.swigCPtr == ((FMOD_VECTOR)obj).swigCPtr;
  }
  public int hashCode() {
     return (int)swigCPtr;
  }

  public void setX(float value) {
    FMODJNI.FMOD_VECTOR_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return FMODJNI.FMOD_VECTOR_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    FMODJNI.FMOD_VECTOR_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return FMODJNI.FMOD_VECTOR_y_get(swigCPtr, this);
  }

  public void setZ(float value) {
    FMODJNI.FMOD_VECTOR_z_set(swigCPtr, this, value);
  }

  public float getZ() {
    return FMODJNI.FMOD_VECTOR_z_get(swigCPtr, this);
  }

  public FMOD_VECTOR() {
    this(FMODJNI.new_FMOD_VECTOR(), true);
  }

}
