/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public final class FMOD_STUDIO_INSTANCETYPE {
  public final static FMOD_STUDIO_INSTANCETYPE FMOD_STUDIO_INSTANCETYPE_NONE = new FMOD_STUDIO_INSTANCETYPE("FMOD_STUDIO_INSTANCETYPE_NONE");
  public final static FMOD_STUDIO_INSTANCETYPE FMOD_STUDIO_INSTANCETYPE_SYSTEM = new FMOD_STUDIO_INSTANCETYPE("FMOD_STUDIO_INSTANCETYPE_SYSTEM");
  public final static FMOD_STUDIO_INSTANCETYPE FMOD_STUDIO_INSTANCETYPE_EVENTDESCRIPTION = new FMOD_STUDIO_INSTANCETYPE("FMOD_STUDIO_INSTANCETYPE_EVENTDESCRIPTION");
  public final static FMOD_STUDIO_INSTANCETYPE FMOD_STUDIO_INSTANCETYPE_EVENTINSTANCE = new FMOD_STUDIO_INSTANCETYPE("FMOD_STUDIO_INSTANCETYPE_EVENTINSTANCE");
  public final static FMOD_STUDIO_INSTANCETYPE FMOD_STUDIO_INSTANCETYPE_PARAMETERINSTANCE = new FMOD_STUDIO_INSTANCETYPE("FMOD_STUDIO_INSTANCETYPE_PARAMETERINSTANCE");
  public final static FMOD_STUDIO_INSTANCETYPE FMOD_STUDIO_INSTANCETYPE_CUEINSTANCE = new FMOD_STUDIO_INSTANCETYPE("FMOD_STUDIO_INSTANCETYPE_CUEINSTANCE");
  public final static FMOD_STUDIO_INSTANCETYPE FMOD_STUDIO_INSTANCETYPE_BUS = new FMOD_STUDIO_INSTANCETYPE("FMOD_STUDIO_INSTANCETYPE_BUS");
  public final static FMOD_STUDIO_INSTANCETYPE FMOD_STUDIO_INSTANCETYPE_VCA = new FMOD_STUDIO_INSTANCETYPE("FMOD_STUDIO_INSTANCETYPE_VCA");
  public final static FMOD_STUDIO_INSTANCETYPE FMOD_STUDIO_INSTANCETYPE_BANK = new FMOD_STUDIO_INSTANCETYPE("FMOD_STUDIO_INSTANCETYPE_BANK");
  public final static FMOD_STUDIO_INSTANCETYPE FMOD_STUDIO_INSTANCETYPE_COMMANDREPLAY = new FMOD_STUDIO_INSTANCETYPE("FMOD_STUDIO_INSTANCETYPE_COMMANDREPLAY");
  public final static FMOD_STUDIO_INSTANCETYPE FMOD_STUDIO_INSTANCETYPE_FORCEINT = new FMOD_STUDIO_INSTANCETYPE("FMOD_STUDIO_INSTANCETYPE_FORCEINT", fmodJNI.FMOD_STUDIO_INSTANCETYPE_FORCEINT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FMOD_STUDIO_INSTANCETYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FMOD_STUDIO_INSTANCETYPE.class + " with value " + swigValue);
  }

  private FMOD_STUDIO_INSTANCETYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FMOD_STUDIO_INSTANCETYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FMOD_STUDIO_INSTANCETYPE(String swigName, FMOD_STUDIO_INSTANCETYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FMOD_STUDIO_INSTANCETYPE[] swigValues = { FMOD_STUDIO_INSTANCETYPE_NONE, FMOD_STUDIO_INSTANCETYPE_SYSTEM, FMOD_STUDIO_INSTANCETYPE_EVENTDESCRIPTION, FMOD_STUDIO_INSTANCETYPE_EVENTINSTANCE, FMOD_STUDIO_INSTANCETYPE_PARAMETERINSTANCE, FMOD_STUDIO_INSTANCETYPE_CUEINSTANCE, FMOD_STUDIO_INSTANCETYPE_BUS, FMOD_STUDIO_INSTANCETYPE_VCA, FMOD_STUDIO_INSTANCETYPE_BANK, FMOD_STUDIO_INSTANCETYPE_COMMANDREPLAY, FMOD_STUDIO_INSTANCETYPE_FORCEINT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

