/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public class FMOD_STUDIO_BANK_INFO {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_STUDIO_BANK_INFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_BANK_INFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODJNI.delete_FMOD_STUDIO_BANK_INFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean equals(Object obj) {
  	if(obj == this) return true;
  	if(obj == null) return false;
  	if (! (obj instanceof FMOD_STUDIO_BANK_INFO)) return false;
    return this.swigCPtr == ((FMOD_STUDIO_BANK_INFO)obj).swigCPtr;
  }
  public int hashCode() {
     return (int)swigCPtr;
  }

  public void setSize(int value) {
    FMODJNI.FMOD_STUDIO_BANK_INFO_size_set(swigCPtr, this, value);
  }

  public int getSize() {
    return FMODJNI.FMOD_STUDIO_BANK_INFO_size_get(swigCPtr, this);
  }

  public void setUserdata(SWIGTYPE_p_void value) {
    FMODJNI.FMOD_STUDIO_BANK_INFO_userdata_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserdata() {
    long cPtr = FMODJNI.FMOD_STUDIO_BANK_INFO_userdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setUserdatalength(int value) {
    FMODJNI.FMOD_STUDIO_BANK_INFO_userdatalength_set(swigCPtr, this, value);
  }

  public int getUserdatalength() {
    return FMODJNI.FMOD_STUDIO_BANK_INFO_userdatalength_get(swigCPtr, this);
  }

  public void setOpencallback(SWIGTYPE_p_f_p_q_const__char_p_unsigned_int_p_p_void_p_void__FMOD_RESULT value) {
    FMODJNI.FMOD_STUDIO_BANK_INFO_opencallback_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__char_p_unsigned_int_p_p_void_p_void__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__char_p_unsigned_int_p_p_void_p_void__FMOD_RESULT getOpencallback() {
    long cPtr = FMODJNI.FMOD_STUDIO_BANK_INFO_opencallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__char_p_unsigned_int_p_p_void_p_void__FMOD_RESULT(cPtr, false);
  }

  public void setClosecallback(SWIGTYPE_p_f_p_void_p_void__FMOD_RESULT value) {
    FMODJNI.FMOD_STUDIO_BANK_INFO_closecallback_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_void__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_void__FMOD_RESULT getClosecallback() {
    long cPtr = FMODJNI.FMOD_STUDIO_BANK_INFO_closecallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_void__FMOD_RESULT(cPtr, false);
  }

  public void setReadcallback(SWIGTYPE_p_f_p_void_p_void_unsigned_int_p_unsigned_int_p_void__FMOD_RESULT value) {
    FMODJNI.FMOD_STUDIO_BANK_INFO_readcallback_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_void_unsigned_int_p_unsigned_int_p_void__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_void_unsigned_int_p_unsigned_int_p_void__FMOD_RESULT getReadcallback() {
    long cPtr = FMODJNI.FMOD_STUDIO_BANK_INFO_readcallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_void_unsigned_int_p_unsigned_int_p_void__FMOD_RESULT(cPtr, false);
  }

  public void setSeekcallback(SWIGTYPE_p_f_p_void_unsigned_int_p_void__FMOD_RESULT value) {
    FMODJNI.FMOD_STUDIO_BANK_INFO_seekcallback_set(swigCPtr, this, SWIGTYPE_p_f_p_void_unsigned_int_p_void__FMOD_RESULT.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_unsigned_int_p_void__FMOD_RESULT getSeekcallback() {
    long cPtr = FMODJNI.FMOD_STUDIO_BANK_INFO_seekcallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_unsigned_int_p_void__FMOD_RESULT(cPtr, false);
  }

  public FMOD_STUDIO_BANK_INFO() {
    this(FMODJNI.new_FMOD_STUDIO_BANK_INFO(), true);
  }

}
